<a href="https://colab.research.google.com/github/adigup390/deepintocnn/blob/main/kagglesubmissionLogisticRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
import  numpy as np

In [4]:
data = pd.read_csv("/content/sample_data/train.csv")


In [5]:
data.dropna(subset = ["target"], inplace = True)

In [ ]:
testdata.dropna()

In [6]:
data.head()

id  feature_0  feature_1  ...  feature_73  feature_74   target
0   0          0          0  ...           0           0  Class_6
1   1          0          0  ...           1           0  Class_6
2   2          0          0  ...           0           0  Class_2
3   3          0          0  ...           3           0  Class_8
4   4          1          0  ...           0           0  Class_2

[5 rows x 77 columns]

In [7]:
train, test = train_test_split(data, test_size=0.2)
#training_data = train[:,1:76]
#test_data = test[:,1:76]
train

id  feature_0  feature_1  ...  feature_73  feature_74   target
187689  187689          4          0  ...           0           1  Class_9
199871  199871          2          0  ...           2           0  Class_8
5917      5917          0          0  ...           0           0  Class_1
188617  188617          0          0  ...           0           1  Class_8
170971  170971          0          0  ...           0           0  Class_2
...        ...        ...        ...  ...         ...         ...      ...
145653  145653          0          0  ...           0           0  Class_4
22696    22696          0          0  ...           0           0  Class_2
14604    14604          0          0  ...           0           0  Class_9
92600    92600          0          0  ...           0           0  Class_8
39464    39464          0          0  ...           0           0  Class_5

[160000 rows x 77 columns]

In [8]:
label = {"Class_1":0, "Class_2":1, "Class_3":2,"Class_4":3,"Class_5":4,"Class_6":5,"Class_7":6,"Class_8":7,"Class_9":8}

In [9]:
#data.Gender = [gender[item] for item in data.Gender]
train.target = train["target"].map(label)

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:5170: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


In [10]:
test.target = test["target"].map(label)

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:5170: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


In [11]:
test.head()

id  feature_0  feature_1  ...  feature_73  feature_74  target
158805  158805          0          0  ...           0           1       3
144695  144695          0          0  ...           0           0       1
19047    19047          1          0  ...           0           0       2
110909  110909          0          0  ...           0           0       6
17166    17166         30          1  ...           0           0       7

[5 rows x 77 columns]

In [12]:
train = train.to_numpy()
test = test.to_numpy()

In [13]:
train

array([[187689,      4,      0, ...,      0,      1,      8],
       [199871,      2,      0, ...,      2,      0,      7],
       [  5917,      0,      0, ...,      0,      0,      0],
       ...,
       [ 14604,      0,      0, ...,      0,      0,      8],
       [ 92600,      0,      0, ...,      0,      0,      7],
       [ 39464,      0,      0, ...,      0,      0,      4]])

In [14]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
# fit scaler on data
#scaler.fit(train[:,1:76])
# apply transform
train1 = scaler.fit_transform(train)

scaler = StandardScaler()
# fit scaler on data
scaler.fit(test)
# apply transform
test1 = scaler.transform(test)

In [15]:
train[0]

array([187689,      4,      0,      0,      0,      0,      1,      0,
            0,      3,      0,     11,      1,      0,      0,      0,
            0,      1,      1,      0,      0,      1,      0,      0,
            0,      0,      0,      0,      0,      0,      0,      0,
            0,      0,      0,      0,      0,      0,      0,      0,
            0,      0,      0,      1,      0,      0,      0,      0,
            0,      0,      0,      0,      0,      0,      0,      0,
            0,      0,      2,      0,      0,      0,      1,      1,
            0,      3,      0,      0,      0,      4,      1,      0,
            0,      0,      0,      1,      8])

In [16]:
training_data = np.concatenate((train1[:,1:76],train[:,[76]]),axis = 1)

In [17]:
test_data = np.concatenate((test1[:,1:76],test[:,[76]]),axis = 1)

In [18]:
test_data.shape

(40000, 76)

In [19]:

np.unique(training_data[:,75])

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [20]:
import torch

In [21]:
from torchvision import transforms

In [22]:
from torch.utils.data import Dataset
import numpy as np

In [23]:
training_data = torch.tensor(training_data.astype(float))

In [24]:
test_data = torch.tensor(test_data.astype(float))

In [25]:
class my_data(Dataset):
  def __init__(self,training_data,transform = None,target_transform = None):
    self.data = training_data
    self.transform = transform;
    self.target_transform = target_transform;

  def __len__(self):
    return self.data.shape[0];

  def __getitem__(self,idx):
    train = self.data[idx,0:75]
    label = self.data[idx,75]
    if self.transform:
      train = self.transform(train)

    if self.target_transform:
      label = self.target_transform(label)
      
    return train, label

In [26]:
trainset = my_data(training_data,transform=None,target_transform = None)
#testset = my_data(test_data,test_label,transform = transform)

In [27]:
trainloader = torch.utils.data.DataLoader(trainset,batch_size = 100,shuffle = True)
#testloader = torch.utils.data.DataLoader(trainset,batch_size = 64,shuffle = True)

In [28]:
from torch import nn
class LogisticRegression(torch.nn.Module):
  def __init__(self,input_dim,output_dim):
    super(LogisticRegression, self).__init__()
    self.linear = torch.nn.Linear(input_dim, output_dim)
  
  def forward(self,x):
    outputs = self.linear(x)
    return outputs
    

In [29]:
n_iters = 3000
epochs = n_iters
input_dim = 75
output_dim = 9
lr_rate = 0.01

In [30]:
model = LogisticRegression(input_dim, output_dim)

In [31]:
feature, label = next(iter(trainloader))
output = model(feature.float())
out = torch.argmax(output, dim = 1)
print(output)

tensor([[-2.6966e-02,  7.9839e-02,  2.6660e-01,  5.2598e-02,  4.2649e-01,
          3.0514e-01, -1.3754e-01, -7.0472e-02,  4.7940e-03],
        [-4.2054e-02,  6.7245e-02,  5.1552e-01, -2.8234e-01,  5.5042e-01,
         -6.8055e-02,  1.7141e-01, -3.7597e-01, -1.9657e-01],
        [ 1.8818e-01, -1.0452e+00, -1.9805e-01,  8.6868e-01,  4.4169e-01,
          7.4759e-01,  1.3617e+00,  3.7649e-01, -2.6011e-01],
        [ 1.3955e-01,  3.1620e-01,  1.4654e-01, -5.0588e-02,  9.6288e-02,
         -2.1856e-01,  1.8532e-01, -5.8236e-01,  1.4197e-01],
        [-1.9936e-01, -5.9959e-01, -3.1310e-01, -5.8605e-02, -2.4910e-03,
         -4.3353e-01,  3.3796e-01, -3.6013e-01,  9.9604e-02],
        [ 4.0341e-02,  1.6477e-01,  7.1779e-02, -2.8288e-01,  1.5694e-01,
          5.4652e-02,  3.8469e-01,  7.5595e-04, -2.1546e-01],
        [ 2.1574e-01,  8.6341e-02, -3.6458e-03,  7.0975e-02,  1.2385e-01,
          1.9951e-01,  2.9856e-01,  1.2737e-01,  5.7494e-02],
        [-7.9598e-02, -2.1070e-01,  1.1013e-01, 

In [43]:
from torch import optim
optimizer = optim.SGD(model.parameters(),lr = 0.0005)

In [33]:
print(label.shape)

torch.Size([100])


In [38]:
correct = 0
with torch.no_grad():
    input = test_data
    output = model(input[:,0:75].float())
    _, predicted = torch.max(output,dim = 1)
    equals = predicted==test_data[:,75]
    #print(equals.shape)
    correct += torch.sum(torch.tensor(equals)).item()
    #loss = criterion(output,test_data[:,74])
    #test_running_loss += loss
    #test_loss.append(test_running_loss)
    #print(f"test_loss: {test_running_loss}")
    print(f"Accuracy: {correct/40000}")

Accuracy: 0.34405


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  


In [44]:

epochs = 50
criterion = torch.nn.CrossEntropyLoss()
for e in range(epochs):
  running_loss = 0
  for features, labels in iter(trainloader):
    optimizer.zero_grad()
    output = model(features.float())
    #predicted = torch.argmax(output,dim = 1,keepdim = False)
    labels = labels.type(torch.LongTensor)
    loss = criterion(output,labels)
    running_loss+= loss
    loss.backward()
    optimizer.step()
  #training_loss.append(running_loss)
  print(f"Loss = {running_loss}")
  correct = 0
  test_running_loss = 0
  with torch.no_grad():
    input = test_data
    output = model(input[:,0:75].float())
    _, predicted = torch.max(output,dim = 1)
    equals = predicted==test_data[:,75]
    #print(equals.shape)
    correct += torch.sum(torch.tensor(equals)).item()
    #loss = criterion(output,test_data[:,74])
    #test_running_loss += loss
    #test_loss.append(test_running_loss)
    #print(f"test_loss: {test_running_loss}")
    print(f"Accuracy: {correct/40000}")

Loss = 2920.379638671875
Accuracy: 0.344475


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:25: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).


Loss = 2920.37451171875
Accuracy: 0.344525
Loss = 2920.377197265625
Accuracy: 0.34435
Loss = 2920.36669921875
Accuracy: 0.3441
Loss = 2920.36767578125
Accuracy: 0.34425
Loss = 2920.374755859375
Accuracy: 0.344225
Loss = 2920.368896484375
Accuracy: 0.34425
Loss = 2920.364013671875
Accuracy: 0.3443
Loss = 2920.368408203125
Accuracy: 0.3443
Loss = 2920.368408203125
Accuracy: 0.3442
Loss = 2920.367431640625
Accuracy: 0.34415
Loss = 2920.36572265625
Accuracy: 0.3439
Loss = 2920.370849609375
Accuracy: 0.344125
Loss = 2920.36572265625
Accuracy: 0.344225
Loss = 2920.365234375
Accuracy: 0.34405
Loss = 2920.367919921875
Accuracy: 0.34425
Loss = 2920.36767578125
Accuracy: 0.3443
Loss = 2920.36669921875
Accuracy: 0.343875
Loss = 2920.36669921875
Accuracy: 0.344175
Loss = 2920.36572265625
Accuracy: 0.34405
Loss = 2920.36962890625
Accuracy: 0.34405
Loss = 2920.375244140625
Accuracy: 0.344075
Loss = 2920.36962890625
Accuracy: 0.344075
Loss = 2920.3701171875
Accuracy: 0.3442
Loss = 2920.36474609375
Ac

In [86]:
testdata = pd.read_csv("/content/sample_data/test.csv")
testdata.dropna()
test_eval = testdata.iloc[:,1:76]
test_eval = test_eval.to_numpy()

In [87]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
# fit scaler on data
#scaler.fit(train[:,1:76])
# apply transform
test_eval = scaler.fit_transform(test_eval)

In [88]:
test_eval = torch.tensor(test_eval.astype(float))
output = model(test_eval.float())

In [89]:
output

tensor([[-0.5110,  1.2533,  0.4688,  ..., -0.3553,  0.8359,  0.5862],
        [-0.5065,  0.6345,  0.1308,  ..., -0.1674,  1.0620,  0.5973],
        [-0.5092,  0.3775, -0.0654,  ..., -0.1840,  1.0845,  0.5534],
        ...,
        [-0.4866,  1.1806,  0.4375,  ..., -0.3329,  0.8903,  0.5977],
        [-0.3295, -0.4573, -0.4946,  ...,  0.1999,  1.5336,  0.5950],
        [-0.5094,  0.7038,  0.2397,  ..., -0.1745,  1.0112,  0.5756]],
       grad_fn=<AddmmBackward>)

In [91]:
output
output = output.detach().numpy()

In [92]:
output  = np.exp(output)
output

array([[0.59986794, 3.501773  , 1.5981529 , ..., 0.7009818 , 2.30689   ,
        1.7970668 ],
       [0.60262716, 1.8859897 , 1.1397924 , ..., 0.8458949 , 2.8920548 ,
        1.8172616 ],
       [0.6010025 , 1.4586723 , 0.9366597 , ..., 0.8319087 , 2.9579628 ,
        1.7390742 ],
       ...,
       [0.61471194, 3.2564764 , 1.5488174 , ..., 0.71681774, 2.4358127 ,
        1.8178483 ],
       [0.71927583, 0.63301396, 0.6098117 , ..., 1.2213174 , 4.6347704 ,
        1.8130188 ],
       [0.60086966, 2.0213594 , 1.2708777 , ..., 0.8398767 , 2.7488065 ,
        1.7782849 ]], dtype=float32)

In [103]:
x = np.sum(output, axis = 1, keepdims = True)
print(output.shape)
x.shape

(100000, 9)


(100000, 1)

In [105]:
output1 = output/x
print(np.sum(output1, axis = 1))

[0.9999999  0.99999994 1.         ... 1.         0.99999994 1.        ]


In [106]:
print(output.astype(float))

[[0.59986794 3.50177312 1.59815288 ... 0.7009818  2.30689001 1.79706681]
 [0.60262716 1.88598967 1.13979244 ... 0.84589487 2.8920548  1.81726158]
 [0.60100251 1.45867229 0.93665969 ... 0.8319087  2.95796275 1.73907423]
 ...
 [0.61471194 3.2564764  1.5488174  ... 0.71681774 2.43581271 1.81784832]
 [0.71927583 0.63301396 0.60981172 ... 1.22131741 4.63477039 1.8130188 ]
 [0.60086966 2.02135944 1.27087772 ... 0.83987671 2.74880648 1.77828491]]


In [51]:
testdf = testdata.loc['id']
dftest = pd.DataFrame(output, columns=["Class_1","Class_2","Class_3","Class_4","Class_5","Class_6","Class_7","Class_8","Class_9"])
testdf.append(dftest)

KeyError: ignored

In [81]:
testdata.shape

(100000, 76)

In [107]:
testdf = pd.DataFrame()
testdf['id'] = testdata['id']

In [113]:
dftest = pd.DataFrame(output1, columns=["Class_1","Class_2","Class_3","Class_4","Class_5","Class_6","Class_7","Class_8","Class_9"])
#testdf = pd.concat([testdf,dftest])

In [109]:
testdf.head()

id
0  200000
1  200001
2  200002
3  200003
4  200004

In [114]:
dftest.head()

Class_1   Class_2   Class_3  ...   Class_7   Class_8   Class_9
0  0.042412  0.247584  0.112993  ...  0.049561  0.163103  0.127057
1  0.046513  0.145569  0.087974  ...  0.065290  0.223221  0.140264
2  0.043469  0.105503  0.067747  ...  0.060171  0.213944  0.125784
3  0.044960  0.092879  0.072356  ...  0.075718  0.272094  0.142423
4  0.037445  0.085563  0.063174  ...  0.070774  0.274880  0.136287

[5 rows x 9 columns]

In [115]:
testdf.head()

id
0  200000
1  200001
2  200002
3  200003
4  200004

In [66]:
del(testdf)

In [116]:
testdf1 = pd.concat([testdf,dftest],axis = 1)

In [117]:
testdf1.head()

id   Class_1   Class_2   Class_3  ...   Class_6   Class_7   Class_8   Class_9
0  200000  0.042412  0.247584  0.112993  ...  0.223116  0.049561  0.163103  0.127057
1  200001  0.046513  0.145569  0.087974  ...  0.253848  0.065290  0.223221  0.140264
2  200002  0.043469  0.105503  0.067747  ...  0.346530  0.060171  0.213944  0.125784
3  200003  0.044960  0.092879  0.072356  ...  0.255064  0.075718  0.272094  0.142423
4  200004  0.037445  0.085563  0.063174  ...  0.297297  0.070774  0.274880  0.136287

[5 rows x 10 columns]

In [118]:
testdf1.to_csv('/content/sample_data/output1.csv',index = False)