In [33]:
import numpy as np
val1 = [1,2,3,4,5]
arr1 = np.array(val1)
arr1

array([1, 2, 3, 4, 5])

In [34]:
data2 = [range(1, 5), range(5, 9)]  # list of lists
arr2 = np.array(data2,dtype = object)              # 2d array
print(*data2)
print(*arr2)
arr2.tolist() 

range(1, 5) range(5, 9)
[1 2 3 4] [5 6 7 8]


[[1, 2, 3, 4], [5, 6, 7, 8]]

In [35]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [37]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [38]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [39]:
np.logspace(1,3,4)

array([  10.        ,   46.41588834,  215.443469  , 1000.        ])

In [42]:
int_array = np.arange(1,5)
print(*int_array)

1 2 3 4


In [44]:
float_array = int_array.astype(float)
print(*float_array)

1.0 2.0 3.0 4.0


In [46]:
arr1.dtype

dtype('int64')

In [47]:
arr2.ndim

2

In [49]:
arr2.shape

(2, 4)

In [50]:
arr2.size

8

In [51]:
len(arr2)

2

In [52]:
arr = np.arange(10).reshape((2,5))

In [53]:
print(*arr)

[0 1 2 3 4] [5 6 7 8 9]


In [54]:
arr.shape

(2, 5)

In [55]:
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [76]:
a = np.array([0,1])
a_col = a[:,np.newaxis]
print(a_col)

[[0]
 [1]]


In [77]:
print(a_col.T)

[[0 1]]


In [74]:
arr_flt = arr.flatten()

In [75]:
print(arr_flt)

[0 1 2 3 4 5 6 7 8 9]


In [79]:
x = np.arange(2*3*4)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [80]:
x = x.reshape(2,3,4)
print(x)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [81]:
print(x[1,:,:])

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [85]:
print(x[0,1,:])

[4 5 6 7]


In [84]:
print(x.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [86]:
print(x)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [87]:
print(x.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [89]:
#stacking arrays
a = np.array([1,2])
b = np.array([3,4])
np.hstack([a,b])

array([1, 2, 3, 4])

In [90]:
np.vstack([a,b])

array([[1, 2],
       [3, 4]])

In [91]:
np.stack([a,b])

array([[1, 2],
       [3, 4]])

In [97]:
arr = np.arange(10,dtype = float).reshape((2,5))

In [94]:
arr[0,:]

array([0., 1., 2., 3., 4.])

In [95]:
arr[:,0]

array([0., 5.])

In [96]:
arr[:,:2]

array([[0., 1.],
       [5., 6.]])

In [98]:
arr[:,2:]

array([[2., 3., 4.],
       [7., 8., 9.]])

In [101]:
#slicing returns a view not a copy
print(arr[:,::-1])

[[4. 3. 2. 1. 0.]
 [9. 8. 7. 6. 5.]]


In [102]:
#fancy indexing returns copy not view
print(arr)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]


In [105]:
arr2 = arr[:,[1,2,3]]
print(arr2)

[[1. 2. 3.]
 [6. 7. 8.]]


In [106]:
arr2[0][0] = 56
print(arr2)

[[56.  2.  3.]
 [ 6.  7.  8.]]


In [107]:
print(arr)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]


In [108]:
arr2  = arr[arr>5]

In [109]:
print(arr2)

[6. 7. 8. 9.]


In [110]:
names = np.array(['Bob','Joe','Will','Bob']);
names == 'Bob'

array([ True, False, False,  True])

In [111]:
names

array(['Bob', 'Joe', 'Will', 'Bob'], dtype='<U4')

In [112]:
names[names!='Bob']

array(['Joe', 'Will'], dtype='<U4')

In [113]:
(names == 'Bob') | (names == 'Will')

array([ True, False,  True,  True])

In [114]:
names[names!='Bob'] = 'Joe'

In [115]:
names

array(['Bob', 'Joe', 'Joe', 'Bob'], dtype='<U4')

In [116]:
np.unique(names)

array(['Bob', 'Joe'], dtype='<U4')

In [117]:
nums= np.arange(5)

In [118]:
nums*10

array([ 0, 10, 20, 30, 40])

In [119]:
nums**2

array([ 0,  1,  4,  9, 16])

In [122]:
mums = np.sqrt(nums)

In [123]:
np.ceil(mums)

array([0., 1., 2., 2., 2.])

In [124]:
np.floor(mums)

array([0., 1., 1., 1., 2.])

In [125]:
np.rint(mums)

array([0., 1., 1., 2., 2.])

In [127]:
rnd = np.random.randn(4,2)

In [128]:
rnd

array([[ 0.30440658,  1.05875018],
       [ 0.54024425,  1.29677944],
       [-0.42507504,  1.74266132],
       [ 1.53508563,  0.1651942 ]])

In [129]:
rnd.min()

-0.42507504479487473

In [130]:
rnd.argmin()

4

In [131]:
rnd.max()

1.7426613202676768

In [132]:
rnd.argmax()

5

In [133]:
rnd.sum(axis = 0)

array([1.95466142, 4.26338515])

In [136]:
np.random.randint(0,10,10)

array([9, 3, 7, 9, 7, 1, 3, 5, 7, 6])

In [140]:
np.random.seed(1)
X = np.random.randn(4,2)
print(X)

[[ 1.62434536 -0.61175641]
 [-0.52817175 -1.07296862]
 [ 0.86540763 -2.3015387 ]
 [ 1.74481176 -0.7612069 ]]


In [146]:
X.min(axis = 0)

array([-0.52817175, -2.3015387 ])

In [147]:
X.argmin(axis = 0)

array([1, 2])

In [144]:
def standarize(a):
    a1 = a-a.mean(axis = 0)
    a = a1/a.std(axis = 0)
    return a

In [145]:
standarize(X)

array([[ 0.77095311,  0.86519474],
       [-1.60740108,  0.17134919],
       [-0.0676106 , -1.67690604],
       [ 0.90405856,  0.64036211]])