<a href="https://colab.research.google.com/github/adigup390/deepintocnn/blob/main/kagglesubmission.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
import  numpy as np

In [ ]:
data = pd.read_csv("/content/sample_data/train.csv")
testdata = pd.read_csv("/content/sample_data/test.csv")

In [ ]:
data.dropna(subset = ["target"], inplace = True)

In [ ]:
testdata.dropna()

In [ ]:
data.head()

id  feature_0  feature_1  ...  feature_73  feature_74   target
0   0          0          0  ...           0           0  Class_6
1   1          0          0  ...           1           0  Class_6
2   2          0          0  ...           0           0  Class_2
3   3          0          0  ...           3           0  Class_8
4   4          1          0  ...           0           0  Class_2

[5 rows x 77 columns]

In [ ]:
train, test = train_test_split(data, test_size=0.2)
#training_data = train[:,1:76]
#test_data = test[:,1:76]
train

id  feature_0  feature_1  ...  feature_73  feature_74   target
184626  184626          0          1  ...           0           0  Class_6
3759      3759          0          4  ...           2           0  Class_8
2756      2756          0          0  ...           8          47  Class_3
21328    21328          0          2  ...           1           0  Class_5
22817    22817          0          0  ...           0           0  Class_9
...        ...        ...        ...  ...         ...         ...      ...
199056  199056          0          0  ...           0           0  Class_6
47911    47911          0          0  ...           0           0  Class_2
119189  119189          0          1  ...           0           0  Class_8
123914  123914          0          0  ...           2           0  Class_8
187524  187524          1          0  ...           1           0  Class_9

[160000 rows x 77 columns]

In [ ]:
label = {"Class_1":0, "Class_2":1, "Class_3":2,"Class_4":3,"Class_5":4,"Class_6":5,"Class_7":6,"Class_8":7,"Class_9":8}

In [ ]:
#data.Gender = [gender[item] for item in data.Gender]
train.target = train["target"].map(label)

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:5170: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


In [ ]:
test.target = test["target"].map(label)

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:5170: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


In [ ]:
test.head()

id  feature_0  feature_1  ...  feature_73  feature_74  target
18376    18376          0          0  ...           0           0       1
79363    79363          0          0  ...           2           1       7
146784  146784          0          0  ...           1           0       8
69959    69959          0          0  ...          85           0       7
86987    86987          0          0  ...           5           0       6

[5 rows x 77 columns]

In [ ]:
train = train.to_numpy()
test = test.to_numpy()

In [ ]:
train

array([[184626,      0,      1, ...,      0,      0,      5],
       [  3759,      0,      4, ...,      2,      0,      7],
       [  2756,      0,      0, ...,      8,     47,      2],
       ...,
       [119189,      0,      1, ...,      0,      0,      7],
       [123914,      0,      0, ...,      2,      0,      7],
       [187524,      1,      0, ...,      1,      0,      8]])

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
# fit scaler on data
#scaler.fit(train[:,1:76])
# apply transform
train1 = scaler.fit_transform(train)

scaler = StandardScaler()
# fit scaler on data
scaler.fit(test)
# apply transform
test1 = scaler.transform(test)

In [ ]:
train[0]

array([184626,      0,      1,      1,      1,      0,      0,      0,
            0,      2,      2,      1,      1,      3,      0,      1,
            0,      0,      0,      4,      0,      0,      2,      9,
            1,      0,      0,      2,      0,      1,      0,      0,
            2,      0,      1,      0,      1,      1,      2,      2,
            4,      1,      0,      0,      3,      0,      0,      0,
            0,      1,      0,      0,      0,      0,      6,      0,
            0,      1,      0,      0,      0,      0,      0,      0,
            0,      0,      2,      2,      0,      0,      0,      0,
            0,      1,      0,      0,      5])

In [ ]:
training_data = np.concatenate((train1[:,1:76],train[:,[76]]),axis = 1)

In [ ]:
test_data = np.concatenate((test1[:,1:76],test[:,[76]]),axis = 1)

In [ ]:
test_data.shape

(40000, 76)

In [ ]:

np.unique(training_data[:,75])

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [ ]:
import torch

In [ ]:
from torchvision import transforms

In [ ]:
from torch.utils.data import Dataset
import numpy as np

In [ ]:
training_data = torch.tensor(training_data.astype(float))

In [ ]:
test_data = torch.tensor(test_data.astype(float))

In [ ]:
class my_data(Dataset):
  def __init__(self,training_data,transform = None,target_transform = None):
    self.data = training_data
    self.transform = transform;
    self.target_transform = target_transform;

  def __len__(self):
    return self.data.shape[0];

  def __getitem__(self,idx):
    train = self.data[idx,0:75]
    label = self.data[idx,75]
    if self.transform:
      train = self.transform(train)

    if self.target_transform:
      label = self.target_transform(label)
      
    return train, label

In [ ]:
trainset = my_data(training_data,transform=None,target_transform = None)
#testset = my_data(test_data,test_label,transform = transform)

In [ ]:
trainloader = torch.utils.data.DataLoader(trainset,batch_size = 64,shuffle = True)
#testloader = torch.utils.data.DataLoader(trainset,batch_size = 64,shuffle = True)

In [ ]:
from torch import nn
model = nn.Sequential(nn.Linear(75,256),
                      nn.ReLU(),
                      nn.Dropout(p=0.2),
                      nn.Linear(256,256),
                      nn.ReLU(),
                      nn.Linear(256,128),
                      nn.ReLU(),
                      nn.Dropout(p=0.2),
                      nn.Linear(128,64),
                      nn.ReLU(),
                      nn.Dropout(p=0.2),
                      nn.Linear(64,9),
                      nn.LogSoftmax(dim = 1));
print(model)

Sequential(
  (0): Linear(in_features=75, out_features=256, bias=True)
  (1): ReLU()
  (2): Dropout(p=0.2, inplace=False)
  (3): Linear(in_features=256, out_features=256, bias=True)
  (4): ReLU()
  (5): Linear(in_features=256, out_features=128, bias=True)
  (6): ReLU()
  (7): Dropout(p=0.2, inplace=False)
  (8): Linear(in_features=128, out_features=64, bias=True)
  (9): ReLU()
  (10): Dropout(p=0.2, inplace=False)
  (11): Linear(in_features=64, out_features=9, bias=True)
  (12): LogSoftmax(dim=1)
)


In [ ]:
feature, label = next(iter(trainloader))
output = model(feature.float())
out = torch.argmax(output, dim = 1)
print(output)

tensor([[-2.1347, -2.0631, -2.3001, -2.2797, -2.1635, -2.2093, -2.1897, -2.3498,
         -2.1198],
        [-2.1742, -2.0347, -2.2862, -2.2713, -2.2281, -2.1906, -2.2206, -2.2770,
         -2.1200],
        [-2.1519, -2.0595, -2.2886, -2.2781, -2.1332, -2.2022, -2.1770, -2.3772,
         -2.1445],
        [-2.1437, -2.0487, -2.2830, -2.2815, -2.1868, -2.1900, -2.2196, -2.3171,
         -2.1339],
        [-2.1628, -2.0693, -2.2837, -2.2853, -2.1311, -2.1934, -2.1925, -2.3695,
         -2.1230],
        [-2.1432, -2.0770, -2.2812, -2.2986, -2.1424, -2.1867, -2.1978, -2.3460,
         -2.1336],
        [-2.1363, -2.0686, -2.2775, -2.2787, -2.1541, -2.1989, -2.1945, -2.3875,
         -2.1171],
        [-2.1252, -2.0701, -2.2723, -2.2847, -2.1457, -2.2199, -2.2073, -2.3783,
         -2.1101],
        [-2.1169, -2.0868, -2.2858, -2.2830, -2.1624, -2.2213, -2.1855, -2.3530,
         -2.1135],
        [-2.1724, -2.0265, -2.2773, -2.2960, -2.2139, -2.2213, -2.1998, -2.3034,
         -2.0988],


In [ ]:
from torch import optim
optimizer = optim.SGD(model.parameters(),lr = 0.002)

In [ ]:
print(label.shape)

torch.Size([64])


In [ ]:
with torch.no_grad():
    input = test_data
    output = model(input[:,0:75].float())
    _, predicted = torch.max(output,dim = 1)
    equals = predicted==test_data[:,75]
    #print(equals.shape)
    correct += torch.sum(torch.tensor(equals)).item()
    #loss = criterion(output,test_data[:,74])
    #test_running_loss += loss
    #test_loss.append(test_running_loss)
    #print(f"test_loss: {test_running_loss}")
    print(f"Accuracy: {correct/40000}")

NameError: ignored

In [ ]:

epochs = 200
criterion = nn.NLLLoss()
for e in range(epochs):
  running_loss = 0
  for features, labels in iter(trainloader):
    optimizer.zero_grad()
    output = model(features.float())
    #predicted = torch.argmax(output,dim = 1,keepdim = False)
    labels = labels.type(torch.LongTensor)
    loss = criterion(output,labels)
    running_loss+= loss
    loss.backward()
    optimizer.step()
  #training_loss.append(running_loss)
  print(f"Loss = {running_loss}")
  correct = 0
  test_running_loss = 0
  with torch.no_grad():
    input = test_data
    output = model(input[:,0:75].float())
    _, predicted = torch.max(output,dim = 1)
    equals = predicted==test_data[:,75]
    #print(equals.shape)
    correct += torch.sum(torch.tensor(equals)).item()
    #loss = criterion(output,test_data[:,74])
    #test_running_loss += loss
    #test_loss.append(test_running_loss)
    #print(f"test_loss: {test_running_loss}")
    print(f"Accuracy: {correct/40000}")

Loss = 3920.504638671875


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:25: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).


Accuracy: 0.317825
Loss = 3917.99560546875
Accuracy: 0.3194
Loss = 3908.44140625
Accuracy: 0.320675
Loss = 3913.802734375
Accuracy: 0.3201
Loss = 3907.45751953125
Accuracy: 0.319225
Loss = 3910.392822265625
Accuracy: 0.32005
Loss = 3910.93017578125
Accuracy: 0.31855
Loss = 3906.63916015625
Accuracy: 0.3188
Loss = 3911.057373046875
Accuracy: 0.319775
Loss = 3911.469970703125
Accuracy: 0.31995
Loss = 3907.427734375
Accuracy: 0.3202
Loss = 3902.996826171875
Accuracy: 0.318125
Loss = 3905.73193359375
Accuracy: 0.3192
Loss = 3904.9033203125
Accuracy: 0.315675
Loss = 3909.08447265625
Accuracy: 0.31755
Loss = 3903.55224609375
Accuracy: 0.318125
Loss = 3900.4248046875
Accuracy: 0.315875
Loss = 3901.4775390625
Accuracy: 0.317325
Loss = 3905.420654296875
Accuracy: 0.3194
Loss = 3903.287353515625
Accuracy: 0.3163


KeyboardInterrupt: ignored

In [ ]:
testdata.dropna()
test_eval = testdata.iloc[:,1:76]
test_eval = test_eval.to_numpy()

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
# fit scaler on data
#scaler.fit(train[:,1:76])
# apply transform
test_eval = scaler.fit_transform(test_eval)

In [ ]:
test_eval = torch.tensor(test_eval.astype(float))
output = model(test_eval.float())

RuntimeError: ignored

In [ ]:
output
output = output.detach().numpy()

In [ ]:
output  = np.exp(output)
output

array([[2.9987155e-02, 7.3656472e-03, 9.8792696e-03, ..., 8.0535844e-02,
        5.7257473e-01, 7.2962768e-02],
       [4.4513579e-02, 3.6160515e-03, 6.9320765e-03, ..., 1.2610745e-01,
        4.1662833e-01, 9.5464222e-02],
       [1.2100006e-01, 5.8468577e-04, 3.3366757e-03, ..., 3.5091072e-01,
        2.4056035e-01, 1.7321423e-01],
       ...,
       [3.5102550e-02, 1.0823917e-02, 1.4456166e-02, ..., 8.5021839e-02,
        4.0498018e-01, 8.4798731e-02],
       [4.6785578e-02, 2.0253792e-04, 1.0897365e-03, ..., 2.8255793e-01,
        5.3386950e-01, 8.2715333e-02],
       [1.1701982e-02, 5.0998462e-04, 1.3967449e-03, ..., 5.7506453e-02,
        8.6510038e-01, 2.4903674e-02]], dtype=float32)

In [ ]:
print(output.astype(float))

[[2.99871545e-02 7.36564724e-03 9.87926964e-03 ... 8.05358440e-02
  5.72574735e-01 7.29627684e-02]
 [4.45135795e-02 3.61605152e-03 6.93207653e-03 ... 1.26107454e-01
  4.16628331e-01 9.54642221e-02]
 [1.21000059e-01 5.84685768e-04 3.33667570e-03 ... 3.50910723e-01
  2.40560353e-01 1.73214227e-01]
 ...
 [3.51025499e-02 1.08239166e-02 1.44561660e-02 ... 8.50218385e-02
  4.04980183e-01 8.47987309e-02]
 [4.67855781e-02 2.02537922e-04 1.08973647e-03 ... 2.82557935e-01
  5.33869505e-01 8.27153325e-02]
 [1.17019815e-02 5.09984617e-04 1.39674486e-03 ... 5.75064532e-02
  8.65100384e-01 2.49036737e-02]]


In [ ]:
testdf = testdata.loc['id']
dftest = pd.DataFrame(output, columns=["Class_1","Class_2","Class_3","Class_4","Class_5","Class_6","Class_7","Class_8","Class_9"])
testdf.append(dftest)

KeyError: ignored

In [ ]:
testdata.head()

id  feature_0  feature_1  ...  feature_72  feature_73  feature_74
0  200000          0          0  ...           0           0           0
1  200001          1          2  ...           3           0           0
2  200002          0          1  ...           2           0           0
3  200003          0          0  ...           4           0           0
4  200004          0          0  ...           0           1           0

[5 rows x 76 columns]

In [ ]:
testdf = pd.DataFrame()
testdf['id'] = testdata['id']

In [ ]:
dftest = pd.DataFrame(output, columns=["Class_1","Class_2","Class_3","Class_4","Class_5","Class_6","Class_7","Class_8","Class_9"])
testdf = pd.concat([testdf,dftest])

In [ ]:
testdf.head()

0  Class_1  Class_2  Class_3  ...  Class_6  Class_7  Class_8  Class_9
0  200000.0      NaN      NaN      NaN  ...      NaN      NaN      NaN      NaN
1  200001.0      NaN      NaN      NaN  ...      NaN      NaN      NaN      NaN
2  200002.0      NaN      NaN      NaN  ...      NaN      NaN      NaN      NaN
3  200003.0      NaN      NaN      NaN  ...      NaN      NaN      NaN      NaN
4  200004.0      NaN      NaN      NaN  ...      NaN      NaN      NaN      NaN

[5 rows x 10 columns]

In [ ]:
dftest.head()

Class_1   Class_2   Class_3  ...   Class_7   Class_8   Class_9
0  0.029987  0.007366  0.009879  ...  0.080536  0.572575  0.072963
1  0.044514  0.003616  0.006932  ...  0.126107  0.416628  0.095464
2  0.121000  0.000585  0.003337  ...  0.350911  0.240560  0.173214
3  0.004011  0.000017  0.000069  ...  0.015447  0.090406  0.003621
4  0.053953  0.049463  0.049787  ...  0.144208  0.436163  0.180089

[5 rows x 9 columns]

In [ ]:
testdf.head()

id
0  200000
1  200001
2  200002
3  200003
4  200004

In [ ]:
del(testdf)

In [ ]:
testdf1 = pd.concat([testdf,dftest],axis = 1)

In [ ]:
testdf1.head()

id   Class_1   Class_2   Class_3  ...   Class_6   Class_7   Class_8   Class_9
0  200000  0.029987  0.007366  0.009879  ...  0.211170  0.080536  0.572575  0.072963
1  200001  0.044514  0.003616  0.006932  ...  0.284522  0.126107  0.416628  0.095464
2  200002  0.121000  0.000585  0.003337  ...  0.005866  0.350911  0.240560  0.173214
3  200003  0.004011  0.000017  0.000069  ...  0.884856  0.015447  0.090406  0.003621
4  200004  0.053953  0.049463  0.049787  ...  0.038069  0.144208  0.436163  0.180089

[5 rows x 10 columns]

In [ ]:
testdf1.to_csv('/content/sample_data/output1.csv',index = False)