In [41]:
import torch
import numpy as np

In [42]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [43]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [44]:
x_ones = torch.ones_like(x_data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [46]:
x_rand = torch.rand_like((x_data),dtype = torch.float) #this will overridde the datatype of x_data
print(x_rand)

tensor([[0.3697, 0.7320],
        [0.1609, 0.1795]])


In [51]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
print(rand_tensor)
ones_tensor = torch.ones(shape)
print(ones_tensor)
zeros_tensor = torch.zeros(shape)
print(zeros_tensor)

tensor([[0.8447, 0.4947, 0.9290],
        [0.8630, 0.0956, 0.9465]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [60]:
#indexing and slicing
tensor = torch.rand(4,4)
print(tensor)
print(tensor[0])
print(tensor[:,0])
print(tensor[:,-1])


tensor([[0.9989, 0.9971, 0.4654, 0.0701],
        [0.0770, 0.7398, 0.8573, 0.7955],
        [0.9410, 0.4611, 0.5919, 0.3200],
        [0.8322, 0.6526, 0.7122, 0.8202]])
tensor([0.9989, 0.9971, 0.4654, 0.0701])
tensor([0.9989, 0.0770, 0.9410, 0.8322])
tensor([0.0701, 0.7955, 0.3200, 0.8202])


In [61]:
t1 = torch.cat([tensor,tensor,tensor],dim = 1);
print(t1)

tensor([[0.9989, 0.9971, 0.4654, 0.0701, 0.9989, 0.9971, 0.4654, 0.0701, 0.9989,
         0.9971, 0.4654, 0.0701],
        [0.0770, 0.7398, 0.8573, 0.7955, 0.0770, 0.7398, 0.8573, 0.7955, 0.0770,
         0.7398, 0.8573, 0.7955],
        [0.9410, 0.4611, 0.5919, 0.3200, 0.9410, 0.4611, 0.5919, 0.3200, 0.9410,
         0.4611, 0.5919, 0.3200],
        [0.8322, 0.6526, 0.7122, 0.8202, 0.8322, 0.6526, 0.7122, 0.8202, 0.8322,
         0.6526, 0.7122, 0.8202]])


In [64]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(tensor)
y3 = torch.matmul(tensor,tensor.T, out = y3)
print(f"{y1}\n\n{y2}\n\n{y3}")

tensor([[2.2134, 1.2692, 1.6975, 1.8708],
        [1.2692, 1.9209, 1.1755, 1.8098],
        [1.6975, 1.1755, 1.5507, 1.7679],
        [1.8708, 1.8098, 1.7679, 2.2982]])

tensor([[2.2134, 1.2692, 1.6975, 1.8708],
        [1.2692, 1.9209, 1.1755, 1.8098],
        [1.6975, 1.1755, 1.5507, 1.7679],
        [1.8708, 1.8098, 1.7679, 2.2982]])

tensor([[2.2134, 1.2692, 1.6975, 1.8708],
        [1.2692, 1.9209, 1.1755, 1.8098],
        [1.6975, 1.1755, 1.5507, 1.7679],
        [1.8708, 1.8098, 1.7679, 2.2982]])


In [65]:
z1 = tensor*tensor
z2 = tensor.mul(tensor)

In [66]:
print(f"{z1}\n\n{z2}")

tensor([[0.9977, 0.9942, 0.2166, 0.0049],
        [0.0059, 0.5472, 0.7350, 0.6328],
        [0.8854, 0.2126, 0.3503, 0.1024],
        [0.6925, 0.4258, 0.5073, 0.6727]])

tensor([[0.9977, 0.9942, 0.2166, 0.0049],
        [0.0059, 0.5472, 0.7350, 0.6328],
        [0.8854, 0.2126, 0.3503, 0.1024],
        [0.6925, 0.4258, 0.5073, 0.6727]])


In [69]:
agg = tensor.sum()
agg1 = agg.item()
print(agg.shape,type(agg1))

torch.Size([]) <class 'float'>


In [72]:
#inplace operations deonted by _suffix
print(tensor)
tensor.add(5)
print(tensor)
tensor.add_(5)
print(tensor)

tensor([[0.9989, 0.9971, 0.4654, 0.0701],
        [0.0770, 0.7398, 0.8573, 0.7955],
        [0.9410, 0.4611, 0.5919, 0.3200],
        [0.8322, 0.6526, 0.7122, 0.8202]])
tensor([[0.9989, 0.9971, 0.4654, 0.0701],
        [0.0770, 0.7398, 0.8573, 0.7955],
        [0.9410, 0.4611, 0.5919, 0.3200],
        [0.8322, 0.6526, 0.7122, 0.8202]])
tensor([[5.9989, 5.9971, 5.4654, 5.0701],
        [5.0770, 5.7398, 5.8573, 5.7955],
        [5.9410, 5.4611, 5.5919, 5.3200],
        [5.8322, 5.6526, 5.7122, 5.8202]])
